[package]
name = "p01-jira-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.138"

[dev-dependencies]
tempfile = "3.16.0"